version: "2"

services:

  mysql:
    image: mysql:5.7
    ports:
    - 3306:3306
    environment:
    - MYSQL_DATABASE=database
    - MYSQL_ROOT_PASSWORD=root_pass
    - MYSQL_ROOT_HOST=%
    - MYSQL_USER=user
    - MYSQL_PASSWORD=pass
    volumes:
    - ./databases/mysql:/var/lib/mysql
    - ./logs/mysql:/var/log/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
    - 8080:80
    environment:
    - PMA_HOST=mysql
    - PMA_USER=root
    - PMA_PASSWORD=root_pass

  laravel:
    image: evilfreelancer/dockavel:latest
    restart: unless-stopped
    env_file:
    - .env
    links:
    - mysql
    ports:
    - 80:80
    volumes:
    - ./laravel:/app:rw
    - ./logs/laravel:/var/log/apache2:rw
